version: '3.8'

services:
  # التطبيق الرئيسي
  telegram-whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - XAI_API_KEY=${XAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - whatsapp_session:/app/whatsapp-session
      - bot_logs:/app/logs
      - bot_backups:/app/backups
    networks:
      - bot_network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis للتخزين المؤقت
  redis:
    image: redis:7-alpine
    container_name: telegram-whatsapp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot_network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}

  # Nginx كـ Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: telegram-whatsapp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - bot_network
    depends_on:
      - telegram-whatsapp-bot

  # مراقبة الحاويات
  watchtower:
    image: containrrr/watchtower
    container_name: telegram-whatsapp-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
    networks:
      - bot_network

volumes:
  whatsapp_session:
    driver: local
  bot_logs:
    driver: local
  bot_backups:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  bot_network:
    driver: bridge
